kind: pipeline
name: default

steps:
  - name: publish-ubuntu-sits
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      context: docker/ubuntu
      dockerfile: docker/ubuntu/Dockerfile
      repo: brazildatacube/sits-base
      cache_from: "brazildatacube/sits-base:latest"
      tags:
        - ubuntu-20.04
        - latest
    when:
      event:
        - tag

  - name: publish-R-sits
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      context: docker/R
      dockerfile: docker/R/Dockerfile
      repo: brazildatacube/sits-r
      cache_from: "brazildatacube/sits-r:latest"
      tags:
        - "4"
        - latest
      build_args:
        - SITS_ENVIRONMENT_TYPE=full
        - SITS_TAG_VERSION=v${DRONE_SEMVER}
        - BASE_IMAGE=brazildatacube/sits-base:ubuntu-20.04
    when:
      event:
        - tag

  - name: publish-sits
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      context: docker/sits
      dockerfile: docker/sits/Dockerfile
      repo: brazildatacube/sits
      cache_from: "brazildatacube/sits:latest"
      tags:
        - latest
        - ${DRONE_SEMVER}
      build_args:
        - BASE_IMAGE=brazildatacube/sits-r:4
    when:
      event:
        - tag

  - name: publish-rstudio-sits
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PASS
      context: docker/RStudio
      dockerfile: docker/RStudio/Dockerfile
      repo: brazildatacube/sits-rstudio
      cache_from: "brazildatacube/sits-rstudio:latest"
      tags:
        - "1.4.1103"
        - latest
      build_args:
        - BASE_IMAGE=brazildatacube/sits:${DRONE_SEMVER}
    when:
      event:
        - tag
